import CoreImage
import CoreImage.CIFilterBuiltins
import UIKit

/// Renders a profile's share link as a scannable QR code.
///
/// Pure and synchronous: a URL in, a bitmap out, no view involved — so the
/// on-screen card and the shareable image are generated by the same code, and
/// the result can be decoded back in tests (see `ProfileQRCodeTests`, which
/// scans what this produces rather than trusting it).
enum ProfileQRCode {
    /// Error-correction level **H** — the highest, recovering ~30% of a
    /// damaged code. Chosen not for damage but for *occlusion*: the card
    /// centres the profile's avatar on top of the code, and those modules are
    /// simply gone as far as a scanner is concerned. H buys the headroom that
    /// makes the punched centre safe (`ProfileQRCardView.avatarFraction`
    /// keeps the hole far inside that budget).
    static let correctionLevel = "H"

    /// A black-on-white QR image `side` points square.
    ///
    /// - Parameters:
    ///   - url: the payload. Encoded as UTF-8 bytes rather than handed to the
    ///     filter as a string, so a handle with non-ASCII characters survives.
    ///   - side: the rendered side length, in points.
    ///   - scale: the target screen scale.
    static func makeImage(for url: URL, side: CGFloat, scale: CGFloat) -> UIImage? {
        guard side > 0, scale > 0 else { return nil }

        let filter = CIFilter.qrCodeGenerator()
        filter.message = Data(url.absoluteString.utf8)
        filter.correctionLevel = correctionLevel
        guard let output = filter.outputImage else { return nil }

        // The generator emits one PIXEL per module (a ~30pt image). Blowing
        // that up with the default sampling blurs every module edge into its
        // neighbour, which is exactly what a scanner cannot read — so the
        // upscale is an INTEGER factor at nearest-neighbour, which keeps
        // module edges perfectly hard. `samplingNearest()` has to be applied
        // BEFORE the transform: it sets the sampling mode the transform then
        // uses.
        let modules = max(output.extent.width, 1)
        let factor = max(1, ((side * scale) / modules).rounded(.down))
        let enlarged = output.samplingNearest().transformed(by: CGAffineTransform(scaleX: factor, y: factor))

        guard let cgImage = CIContext().createCGImage(enlarged, from: enlarged.extent) else { return nil }

        let format = UIGraphicsImageRendererFormat()
        format.scale = scale
        // Opaque on purpose: a QR must be high-contrast dark-on-light to scan.
        // The generator draws black modules on a CLEAR background, so without
        // this fill the code would composite onto whatever sits behind it —
        // and on a dark backdrop it becomes unscannable.
        format.opaque = true
        let bounds = CGRect(x: 0, y: 0, width: side, height: side)
        return UIGraphicsImageRenderer(size: bounds.size, format: format).image { context in
            UIColor.white.setFill()
            context.fill(bounds)
            // The enlarged bitmap is within one module-pixel of the target, so
            // this last fit is sub-pixel; `.none` keeps it from reintroducing
            // the blur the integer upscale just avoided.
            context.cgContext.interpolationQuality = .none
            UIImage(cgImage: cgImage).draw(in: bounds)
        }
    }
}
